# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CocoaPodsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PKHUD', '~>5.0'
  # Pods for CocoaPodsApp
  

  target 'CocoaPodsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoaPodsAppUITests' do
    # Pods for testing
  end

end
